linux-system-roles/kdump

defaults/main.yml, tasks/main.yml, tasks/ssh.yml, templates/kdump.conf.j2, test/test_ssh.yml
There are two commits. The 1st commit is to add ssh support for kdump role. The 2nd one is adding example code for testing ssh. While customer has to specify ssh_dump_server explicitly, otherwise the test/test_ssh.yml should fail. It may not be fit for CI testing, just an example.
=> Add ssh support for Kdump role

README.md, templates/kdump.conf.j2
`kind` is too obscure.
Fixes #2
=> Rename `dump_target.kind` to `type`

README.md
They are not well tested so we can not consider them stable.
=> Mention that types other than ssh are experimental.

meta/main.yml, tasks/main.yml, tasks/ssh.yml
Fixes indentation in role's metadata:
--> Executing Yamllint on files found in kdump/...
meta/main.yml
9:3       error    wrong indentation: expected 4 but found 2  (indentation)
Fixes 'Find out reserved memory for the crash kernel' task to
never report 'changed' status:
--> Executing Ansible Lint on kdump/tests/tests_default.yml...
[ANSIBLE0012] Commands should not change things if nothing needs doing
kdump/tests/roles/kdump/tasks/main.yml:7
Task/Handler: Find out reserved memory for the crash kernel
=> Fix lint errors, fix checkmode

.github/workflows/tox.yml, molecule/default/molecule.yml, tests/tests_default_wrapper.yml, tests/tests_ssh_wrapper.yml
Deprecate the use of molecule for linting.  Use tox for ansible-lint.
The next step will be to remove the ansible-lint dependency from
the molecule environments.
=> use tox for ansible-lint instead of molecule

tests/tests_ssh.yml
Use the `-` chomping indicator to indicate that the trailing newline is not intended as a part of the string. https://yaml.org/spec/1.1/#chomping/
The trailing newline was causing an actual problem in the test.
Also use the `>` folded style, which is more appropriate here than the `|` literal style.
=> Get rid of the extra final newline in string

tests/tests_default_wrapper.yml, tests/tests_ssh.yml, tests/tests_ssh_wrapper.yml
Updated version of #28. 
The commit sequence is taken mostly from #28 with additional commits on top. It will be squashed to less commits when merging or before.
This change is for the benefit of quick downstream testing when tests run against localhost (a machine in CI) and should have no functional impact on upstream.
=> Add tags to tests

templates/kdump.j2
Fix the kdump.j2 template to work on CentOS 6 too by changing `ansible_distribution == 'RedHat'` to `ansible_os_family == 'RedHat'`.
Enable kdump and perform a reboot on RHEL 6 because by default RHEL 6 image in the CI does not have memory reserved for kdump. This issue only happens with the image, a default installation of RHEL 6 has memory reserved, so fixing it in tests only.
For tests_ssh.yml, manually specify the `netdev` variable in `/sbin/mkdumprd` because by default mkdumprd does not expect the host to connect to itself via SSH. This is an issue with the CI only because the test is single-host.
=> Add `KDUMP_BOOTDIR="/boot"`to `/etc/sysconfig/kdump` for RedHat oses <7

tests/tests_ssh.yml
use `127.0.0.1` for kdump_test_ssh_source if the `SSH_CONNECTION`
env. var. is not defined - this is primarily for testing on a
single host (i.e. the control node is the managed node) for the
basic smoke test.
=> use localhost if no SSH_CONNECTION env. var.

README.md, defaults/main.yml, handlers/main.yml, tasks/main.yml, tests/tests_default.yml, tests/tests_default_reboot.yml, tests/tests_ssh_reboot.yml
**Add kdump_reboot_required for systems with kdump disabled by default**
- Systems that do not have kdump enabled might not have the memory reserved for kdump in /sys/kernel/kexec_crash_size. It is necessary to enable kdump and reboot the system to reserve memory and populate /sys/kernel/kexec_crash_size with the required value.
- Add kdump_reboot_required fact and fail if it is set
- Document the kdump_reboot_required flag in README.md
- Add tests/tasks/execute_with_reboot.yml that runs the role with the rescue block to reboot the managed node if necessary and use this task in tests to run the role.
- Do not skip tasks if kexec_crash_size does not contain the required value. Instead,  configure kdump and request reboot to apply the changes
**Fix /sbin/mkdumprd to point netdev to eth0** …
=> Add reboot required

tasks/main.yml
According to the rhel9 docs:
```
To use the crashkernel default parameters, run the following command:
kdumpctl reset-crashkernel
```
=> use kdumpctl reset-crashkernel on rhel9

CHANGELOG.md
[1.2.5] - 2022-07-19
--------------------
- none
- none
- make min_ansible_version a string in meta/main.yml (#104)
The Ansible developers say that `min_ansible_version` in meta/main.yml
must be a `string` value like `"2.9"`, not a `float` value like `2.9`.
- Add CHANGELOG.md (#105)
=> Version 1.2.5 - CHANGELOG.md [citest skip]

.github/workflows/tox.yml
CI is broken pretty hard right now due to tox 4.x and ansible-test
images.
It will take non-trivial effort to make tox-lsr work with tox 4.x. So,
in the meantime:
* tox-lsr 2.14.1 forces the use of tox 3.x
* tox-lsr 2.14.0 moved to use ansible-core 2.14 which does not support
python 3.8 - rather than try to revert that, I moved some of the
ansible related checks to use python 3.9
* for some reason the latest ansible-test image does not work with
docker - so install the podman-docker package to "fool" the system
into using podman instead of docker - the package is only available on
ubuntu-latest - in order to do this, we first have to remove moby-cli
(aka docker-client)
This isn't pretty, and I have a big plan to replace all of this stuff with
* individual github actions for yamllint, …
=> Use tox-lsr 2.14.1; use py39 for ansible related checks; use podman instead of docker

.github/workflows/tox.yml
This reverts commit dc41ad2ebac1c32bdd9d3630b11299f20cbc6727.
=> Revert "Use tox-lsr 2.14.1; use py39 for ansible related checks; use podman instead of docker (#114)"

templates/kdump.j2
Fixes generation of /etc/sysconfig/kdump in Rocky Linux / etc.
=> Use ansible_os_family in kdump.j2 template

templates/kdump.conf.j2, templates/kdump.j2
Add role name to the generated config files.
```
```
Note: This information is provided to help customers identify that it was generated by System Roles. It may also be used for future analysis.
=> Fingerprint RHEL System Role managed config files

tasks/main.yml, tasks/ssh.yml
ansible-lint now requires `changed_when` even where the command
is conditionally executed
=> ansible-lint - use changed_when even for conditional execution

tests/tasks/check_header.yml, tests/templates/get_ansible_managed.j2, tests/tests_default_reboot.yml
Add the following files: tests/tasks/check_header.yml and
tests/templates/get_ansible_managed.j2.
Use check_header.yml to check generated files for the ansible_managed
and fingerprint headers.
check_header.yml takes these parameters.  `fingerprint` is required,
and one of `__file` or `__file_content`:
* `__file` - the full path of the file to check e.g. `/etc/realmd.conf`
* `__file_content` - the output of `slurp` of the file
* `__fingerprint` - required - the fingerprint string `system_role:$ROLENAME` e.g.
`__fingerprint: "system_role:postfix"`
* `__comment_type` - optional, default `plain` - the type of comments used
e.g. `__comment_type: c` for C/C++-style comments.  `plain` uses `#`.
See https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_filters.html#adding-comments-to-fi …
=> test: check generated files for ansible_managed, fingerprint

tasks/main.yml, templates/kdump.conf.j2, tests/tests_default_reboot.yml
Add tests for crashkernel, dracut_args settings.
Add Fedora as a platform that has support for crashkernel and
dracut_args.
Refactor the code somewhat.
Issue Tracker Tickets (Jira or BZ if any):
https://bugzilla.redhat.com/show_bug.cgi?id=2211272
https://bugzilla.redhat.com/show_bug.cgi?id=2211187
=> test: add test for crashkernel, dracut settings

templates/kdump.conf.j2
Cause: kdump uses the configuration option 'failure_action' instead
of 'default' on EL9 and later.
Consequence: kdump prints a warning to the logs:
kdump: warning: option 'default' was renamed 'failure_action' and will be removed in the future.
please update /etc/kdump.conf to use option 'failure_action' instead.
Fix: Use 'failure_action' on EL9 and later.
Result: kdump works normally on EL9 and later with no warnings to the logs.
=> fix: use failure_action instead of default on EL9 and later

tests/tests_default_reboot.yml
Call the handlers before calling the role again to refresh the configuration.
The role will sometimes fail if the configuration has not been properly
flushed by the handlers before calling the role again.
=> test: call handlers to refresh kdump before calling role again

tasks/ssh.yml
Cause: The evaluation of `__kdump_authorized_keys is defined` was happening
after the evaluation of `(__kdump_authorized_keys.content ...)`.  I guess
the parentheses cause the evaluation to happen first, regardless of the
`if` conditional.
Consequence: If authorized_keys were not found, the role would attempt to
evaluate the undefined `__kdump_authorized_keys` and fail.
Fix: Use the `defined` filter `d` with `__kdump_authorized_keys` to define
the value as an empty line, and omit the `if` clause.
Result: The role does not fail if authorized_keys are missing.
=> fix: do not fail if authorized_keys not found

tasks/ssh.yml, tests/tests_ssh_reboot.yml
Cause: The role does not ensure that the .ssh directory exists for
the kdump_ssh_user on kdump_ssh_server.
Consequence: The role will fail attempting to update the .ssh/authorized_keys
file for the kdump_ssh_user on kdump_ssh_server.
Fix: Ensure the .ssh directory exists for the kdump_ssh_user on kdump_ssh_server.
Result: The role does not fail attempting to update the .ssh/authorized_keys
file for the kdump_ssh_user on kdump_ssh_server.
=> fix: ensure .ssh directory exists for kdump_ssh_user on kdump_ssh_server

tasks/ssh.yml
Cause: There was a race condition if multiple hosts tried to add a key
to the authorized_keys file on kdump_ssh_server at the same time.
Consequence: A key added by one host could be overwritten by a key
added by another host.
Fix: Use the lineinfile module to manage the file - this will ensure
that checking for an existing key, and writing the new key, is done
in one atomic operation on only one host at a time.
Result: A host cannot overwrite the value from another host, and adding
keys is idempotent.
NOTE: You can use the play keyword `serial: 1` to workaround this issue
at the play level.
=> fix: Ensure authorized_keys management works with multiple hosts

tasks/main.yml
Cause: Reading /sys/kernel/kexec_crash_size can report errno 16 - device busy.
Consequence: The role fails because it cannot read the value.
Fix: Retry the read.
Result: The role does not fail if /sys/kernel/kexec_crash_size is busy.
=> fix: retry read of kexec_crash_size

tests/tests_ssh_reboot.yml
Some tests fail like this:
```
TASK [Delete user] *************************************************************
fatal: [/tmp/tmp.cgsy6Vmlnz/RHEL_8_9_TESTING.qcow2]: FAILED! => {
"changed": false,
"name": "kdump_ssh_user",
"rc": 8
}
userdel: user kdump_ssh_user is currently used by process 23050
```
Move the deletion of the user to the last part of the test, and retry
until success or timeout.
=> test: delete kdump user last, retry until success

.ansible-lint, .ostree/README.md, .ostree/get_ostree_data.sh, .ostree/packages-runtime.txt, .sanity-ansible-ignore-2.12.txt, .sanity-ansible-ignore-2.13.txt, .sanity-ansible-ignore-2.14.txt, .sanity-ansible-ignore-2.15.txt, .sanity-ansible-ignore-2.9.txt, README-ostree.md, README.md, meta/collection-requirements.yml, tasks/set_vars.yml, tests/tests_ssh_reboot.yml, vars/main.yml
Feature: Allow running and testing the role with ostree managed nodes.
Reason: We have users who want to use the role to manage ostree
systems.
Result: Users can use the role to manage ostree managed nodes.
=> feat: support for ostree systems

.ansible-lint, .ostree/get_ostree_data.sh, meta/collection-requirements.yml, tasks/main.yml, tasks/set_vars.yml, tests/tests_ssh_reboot.yml
The dependency on `ansible.utils.update_fact` is causing issue with
some users who now must install that collection in order to run
the role, even if they do not care about ostree.
The fix is to stop trying to set `ansible_facts.pkg_mgr`, and instead
force the use of the ostree package manager with the `package:` module
`use:` option.  The strategy is - on ostree systems, set the flag
`__$ROLENAME_is_ostree` if the system is an ostree system.  The flag
will either be undefined or `false` on non-ostree systems.
Then, change every invocation of the `package:` module like this:
```yaml
- name: Ensure required packages are present
package:
name: "{{ __$ROLENAME_packages }}"
state: present
use: "{{ (__$ROLENAME_is_ostree | d(false)) |
ternary('ansible.posix.rhel_rpm_ostree', omit) }}"
```
This …
=> refactor: improve support for ostree systems

tests/tests_ssh.yml, tests/tests_ssh_reboot.yml
Use a unique value of `kdump_path` for each test so we don't have
any conflicts.
Ensure `kdump_path` is removed after the test.
=> test: clean up kdump_path

.ostree/packages-runtime-CentOS-10.txt, .ostree/packages-runtime-RedHat-10.txt, tasks/set_vars.yml, vars/CentOS_10.yml, vars/RedHat_10.yml
Cause: The kdump tools in el10 are split into kexec-tools and
kdump-utils.
Consequence: The kdump role does not have all of the packages
required.
Fix: Install both kexec-tools and kdump-utils on el10.
Result: The kdump system role has all of the packages and
tools required at runtime.
Jira issue: https://issues.redhat.com/browse/RHEL-40071
=> fix: el10 kdump role should depend on kdump-utils
